### ISSUE TITLE
some questions about the code

### ISSUE THREAD

**Issue by xiaoyao2346** [Rapisurazurite/CamoDiffusion#10]
Hello,I am very interested in your work on camodiffusion, but I have been confused about your code for a while. In your file train.py, you instantiate three objects called cond_uvit,model, and diffusion_model. cond_uvit comes from the class model.net.EmptyObject, which is an empty class that does nothing. You pass cond_uvit to the model from model.net.net class via unet=cond_uvit, but there's nothing to do with unet in the constructor at all. I am wondering where the unet network in your diffusion model comes from. Could you please answer my questions? Thanks

**Comment by xiaoyao2346** [comment]
I am sorry, but I still can't find where you said the Unet model is initialized in model.net.net,could you tell me?
![image](https://github.com/user-attachments/assets/a65055f1-992b-4ba9-b46d-d1a11d726e89)

**Comment by Rapisurazurite** [comment]
We utilize a simple U-Net in the "Decoder", which consists of both downsampling and upsampling components.

**Comment by xiaoyao2346** [comment]
Oh,I see, thanks
