### ISSUE TITLE
some questions about the Adaptive Transformer Conditional Network

### ISSUE THREAD

**Issue by Yager-42** [Rapisurazurite/CamoDiffusion#12]
Hello! I am interested in your work on CamoDiffusion. Could you please tell me how the Adaptive Transformer Conditional Network was trained? I have found that you have modified the PVT code to form the ATCN. However, it seems that the weight of it has been loaded at the beginning of the training process. I am wondering if you have retrained a new PVT,  or if you just load a normal PVT weight into the ATCN and the weights of the rest of the modules in the ATCN, excluding the PVT, randomly initialized?

**Comment by Rapisurazurite** [comment]
Certainly, you can directly replace the PVT model with the one from the timm library, and the performance should remain comparable.
